[scaffold]
version = "0.1.1"
cache_root = ".scaffold/lez-cache"

[repos.lez]
url = "https://github.com/logos-blockchain/logos-execution-zone.git"
source = "https://github.com/logos-blockchain/logos-execution-zone.git"
path = ".scaffold/lez-cache/repos/lez/9fa541f3d1cfa2d4415b7c3cf4cd8954a83b78c7"
pin = "9fa541f3d1cfa2d4415b7c3cf4cd8954a83b78c7"

[wallet]
home_dir = ".scaffold/wallet"

[framework]
kind = "default"
version = "0.1.0"

[framework.idl]
spec = "lssa-idl/0.1.0"
path = "idl"

[localnet]
port = 3040
risc0_dev_mode = true
