use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_dir = PathBuf::from(&crate_dir).join("include");
    std::fs::create_dir_all(&output_dir).unwrap();

    let mut config = cbindgen::Config::from_file("cbindgen.toml").unwrap();
    // Rust 2024 edition uses #[unsafe(no_mangle)] which cbindgen 0.27 doesn't
    // fully parse. Manually declare FFI functions via after_includes.
    // The typedef for ProgressCallback is auto-generated by cbindgen before
    // after_includes content, so ordering is correct.
    config.after_includes = Some(String::new());

    // Validate that cbindgen can still parse the crate (catches syntax errors).
    let _bindings = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate C bindings");

    // Write the full header manually (cbindgen 0.27 can't parse #[unsafe(no_mangle)]).
    let header = r#"#ifndef SWAP_FFI_H
#define SWAP_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Callback invoked on each progress event (called from a worker thread).
 */
typedef void (*ProgressCallback)(const char*, void*);

/**
 * Callback invoked when Rust needs to publish a message via the delivery module.
 * Parameters: (topic, payload_json, user_data).
 */
typedef void (*MessagingSendCallback)(const char*, const char*, void*);

char *swap_ffi_load_env(const char *path);

char *swap_ffi_run_maker(const char *config_json,
                         const char *hashlock_hex,
                         ProgressCallback cb,
                         void *user_data);

char *swap_ffi_run_taker(const char *config_json,
                         const char *preimage_hex,
                         ProgressCallback cb,
                         void *user_data);

char *swap_ffi_refund_lez(const char *config_json,
                          const char *hashlock_hex);

char *swap_ffi_refund_eth(const char *config_json,
                          const char *swap_id_hex);

char *swap_ffi_fetch_balances(const char *config_json);

char *swap_ffi_run_maker_loop(const char *config_json,
                              ProgressCallback cb,
                              void *user_data,
                              MessagingSendCallback send_cb,
                              void *send_data);

void swap_ffi_stop_maker_loop(void);

void swap_ffi_free_string(char *ptr);

#ifdef __cplusplus
}
#endif

#endif  /* SWAP_FFI_H */
"#;

    std::fs::write(output_dir.join("swap_ffi.h"), header).unwrap();
}
