#!/usr/bin/env bash
# Starts Anvil, deploys EthHTLC, writes .env with all config values.
#
# Prerequisites:
#   - anvil (from foundry) installed
#   - forge installed
#   - LEZ services running (see below)
#
# LEZ setup (3 terminals in logos-blockchain repos):
#   1) logos-blockchain node:
#      cd logos-blockchain && ./target/debug/logos-blockchain-node nodes/node/config-one-node.yaml
#   2) LSSA indexer:
#      cd lssa && RUST_LOG=info cargo run --release -p indexer_service $(pwd)/integration_tests/configs/indexer/indexer_config.json
#   3) LSSA sequencer:
#      cd lssa && RUST_LOG=info RISC0_DEV_MODE=1 cargo run --release -p sequencer_runner sequencer_runner/configs/debug
#
# Usage:
#   ./scripts/local-setup.sh          # start anvil + deploy + write .env
#   ./scripts/local-setup.sh --no-anvil  # skip anvil (already running)

set -euo pipefail
cd "$(dirname "$0")/.."

NO_ANVIL=false
if [[ "${1:-}" == "--no-anvil" ]]; then
    NO_ANVIL=true
fi

# --- Anvil ---
ANVIL_PID=""
if [[ "$NO_ANVIL" == false ]]; then
    echo "Starting Anvil..."
    anvil --block-time 1 &>/dev/null &
    ANVIL_PID=$!
    sleep 1
    echo "  Anvil running (PID $ANVIL_PID)"
fi

# --- Deploy EthHTLC ---
echo "Deploying EthHTLC to Anvil..."
DEPLOY_OUTPUT=$(cd contracts && \
    PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
    forge script script/DeployEthHTLC.s.sol:DeployEthHTLC \
    --rpc-url http://127.0.0.1:8545 --broadcast 2>&1)

ETH_HTLC_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "EthHTLC deployed at:" | awk '{print $NF}')
if [[ -z "$ETH_HTLC_ADDRESS" ]]; then
    echo "ERROR: Failed to extract contract address from deploy output"
    echo "$DEPLOY_OUTPUT"
    exit 1
fi
echo "  EthHTLC deployed at: $ETH_HTLC_ADDRESS"

# --- Write .env ---
cat > .env <<EOF
# Generated by scripts/local-setup.sh

# Ethereum (Anvil)
ETH_RPC_URL=ws://127.0.0.1:8545
ETH_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ETH_HTLC_ADDRESS=$ETH_HTLC_ADDRESS
ETH_RECIPIENT_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
ETH_AMOUNT=1
ETH_TIMELOCK_MINUTES=5

# LEZ (local sequencer)
LEZ_SEQUENCER_URL=http://localhost:8080
LEZ_SIGNING_KEY=0101010101010101010101010101010101010101010101010101010101010101
LEZ_HTLC_PROGRAM_ID=80511b1f4af9b5ecc24b37d505c668e44e3882340339ff21abefc1b2f6c823da
LEZ_TAKER_ACCOUNT_ID=e7ae77c5ef1a05999344af499fc78a1705398d62ed06cf2e1479f6def89a39bc
LEZ_AMOUNT=1
LEZ_TIMELOCK_MINUTES=10

# General
POLL_INTERVAL_MS=2000
EOF

echo ""
echo "Written .env with all config values."
echo ""
echo "Maker account ID: d07ad2e84b27fa00c262f0a1eea0ff35ca0973547e6a106f72f193c2dc838b44"
echo "Taker account ID: e7ae77c5ef1a05999344af499fc78a1705398d62ed06cf2e1479f6def89a39bc"
echo ""
echo "NOTE: Ensure the sequencer's initial_accounts includes both IDs above"
echo "      with sufficient balance (e.g. 1000000 each)."
if [[ -n "$ANVIL_PID" ]]; then
    echo ""
    echo "Anvil running in background (PID $ANVIL_PID). Kill with: kill $ANVIL_PID"
fi
